Update to the package target for OSX.
M    OSX_Resources/InstallationCheck
M    OSX_Resources/update_mac_package_contents.pl
M    OSX_Resources/InstallationCheck.strings
M    Makefile.am

diff --git a/OSX_Resources/InstallationCheck b/OSX_Resources/InstallationCheck
--- a/OSX_Resources/InstallationCheck
+++ b/OSX_Resources/InstallationCheck
@@ -1,5 +1,24 @@
 #!/bin/sh
 #
+# Check the architecture
+
+# use "i386" or "ppc.*" - nake sure to use a regex for PPC!
+
+architecture="ppc.*" 
+
+
+if arch | grep -v "$architecture"
+then
+    if arch | grep "i386"
+    then
+	# You have an intel mac error message
+	exit 115
+    else
+	# PowerPC message
+	exit 116
+    fi
+fi
+
 # Check to make sure the computer is running 10.3 or later.
 
 version=`uname -a | sed 's/.*Darwin Kernel Version \([0-9.]*\):.*/\1/'`
@@ -21,8 +40,8 @@ minor=`echo $version | sed 's/\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\)/\2/'`
 
 if test $major -lt 7 -o $major -eq 7 -a $minor -lt 10
 then
-    # Fail and display message 80
-    exit 112
+    # Fail and display message 17 (exit code - 96)
+    exit 113
 fi
 
 # we need libxml2 2.6.16 according to configure.ac
@@ -33,7 +52,7 @@ minor=`echo $version | sed 's/\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\)/\2/'`
 if test $major -lt 2 -o $major -eq 2 -a $minor -lt 6
 then
     # Fail and display message 81
-    exit 113
+    exit 114
 fi
 
 exit 0
