Updates to the OS/X build so that it is more automatic. No more pmproj file, either. I added <code> tags in the README so that the perl script that updates the Mac version of that file will look decent.
M    OSX_Resources/InstallationCheck
M    OSX_Resources/License.txt
M    OSX_Resources/Info.plist
M    OSX_Resources/InstallationCheck.strings
M    OSX_Resources/ReadMe.txt
M    OSX_Resources/Welcome.html
M    README
M    Makefile.am
D    mac_osx
D    libdap.pmproj

diff --git a/OSX_Resources/InstallationCheck b/OSX_Resources/InstallationCheck
--- a/OSX_Resources/InstallationCheck
+++ b/OSX_Resources/InstallationCheck
@@ -3,13 +3,37 @@
 # Check to make sure the computer is running 10.3 or later.
 
 version=`uname -a | sed 's/.*Darwin Kernel Version \([0-9.]*\):.*/\1/'`
-major=`echo $version | sed 's/\([0-9]\)\.\([0-9]\)\.\([0-9]\)/\1/'`
-minor=`echo $version | sed 's/\([0-9]\)\.\([0-9]\)\.\([0-9]\)/\2/'`
+major=`echo $version | sed 's/\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\)/\1/'`
+minor=`echo $version | sed 's/\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\)/\2/'`
 
 if test $major -lt 7 -o $major -eq 7 -a $minor -lt 9
 then
-    # Warn and display message 16
+    # Warn and display message 16 (the string displayed will be read from 
+    # InstallationCheck.strings using the exit code minus 32 to select the
+    # specific string).
     exit 48
+fi
+
+# we need libcurl 7.10.6 according to configure.ac
+version=`curl-config --version | sed 's/libcurl \([0-9.]*\).*/\1/'`
+major=`echo $version | sed 's/\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\)/\1/'`
+minor=`echo $version | sed 's/\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\)/\2/'`
+
+if test $major -lt 7 -o $major -eq 7 -a $minor -lt 10
+then
+    # Fail and display message 80
+    exit 112
+fi
+
+# we need libxml2 2.6.16 according to configure.ac
+version=`xml2-config --version | sed 's/\([0-9.]*\).*/\1/'`
+major=`echo $version | sed 's/\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\)/\1/'`
+minor=`echo $version | sed 's/\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\)/\2/'`
+
+if test $major -lt 2 -o $major -eq 2 -a $minor -lt 6
+then
+    # Fail and display message 81
+    exit 113
 fi
 
 exit 0
