Merged with release-3-2-8.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -22,7 +22,7 @@
 # 4. Macros for locating various systems (Matlab, etc.)
 # 5. Macros used to test things about the computer/OS/hardware
 #
-# $Id: configure,v 1.78 2001/08/24 17:46:22 jimg Exp $
+# $Id: configure,v 1.79 2001/10/14 01:28:38 jimg Exp $
 
 # 1. Unidata's macros
 #-------------------------------------------------------------------------
@@ -851,14 +851,14 @@ EOF
     
     
 
-    echo $ac_n "checking "for the packages directory"""... $ac_c" 1>&6
-echo "configure:856: checking "for the packages directory"" >&5
+    echo $ac_n "checking for the packages directory""... $ac_c" 1>&6
+echo "configure:856: checking for the packages directory" >&5
     # Where does DODS live?
     
     DODS_PACKAGES_DIR=`ls -1d ${dods_relative}src/packages* 2> /dev/null`
     if test -z "$DODS_PACKAGES_DIR"
     then
-	{ echo "configure: error: "Could not find the third-party packages!"" 1>&2; exit 1; }
+	{ echo "configure: error: *** Could not find the third-party packages!" 1>&2; exit 1; }
     fi
     echo "$ac_t""$DODS_PACKAGES_DIR" 1>&6
     LDFLAGS="$LDFLAGS -L${dods_relative}lib"
@@ -925,7 +925,7 @@ fi
 	    then
 		echo "$ac_t""Found perl version ${perl_ver}." 1>&6
 	    else
-		{ echo "configure: error: perl version: found ${perl_ver} should be at least 5.000." 1>&2; exit 1; }
+		{ echo "configure: error: *** perl version: found ${perl_ver} should be at least 5.000." 1>&2; exit 1; }
 	    fi
 	    ;;
 	*)
@@ -1575,7 +1575,7 @@ echo "configure:1571: checking for gcc/g++ 2.8 or greater" >&5
     case $GCC_VER in
         *egcs*) echo "$ac_t""Found egcs version ${GCC_VER}." 1>&6 ;;
 	[3-9].* | 2.[7-9]*) echo "$ac_t""Found gcc/g++ version ${GCC_VER}" 1>&6 ;;
-        *) { echo "configure: error: must be at least version 2.7.x" 1>&2; exit 1; } ;;
+        *) { echo "configure: error: *** must be at least version 2.7.x" 1>&2; exit 1; } ;;
     esac
     
     echo $ac_n "checking for gcc's libgcc.a""... $ac_c" 1>&6
@@ -2478,7 +2478,7 @@ EOF
 	XDR_INT32=xdr_int
 	XDR_UINT32=xdr_u_int
     else
-	{ echo "configure: error: How do I get a 32 bit integer on this machine?" 1>&2; exit 1; }
+	{ echo "configure: error: *** How do I get a 32 bit integer on this machine?" 1>&2; exit 1; }
     fi
     # I'm using the three arg form of AC_DEFINE_UNQUOTED because autoheader
     # needs the third argument (although I don't quite get the specifics... 
@@ -2526,7 +2526,7 @@ EOF
     then
 	DODS_BYTE="unsigned char"
     else
-	{ echo "configure: error: How do I get an 8 bit unsigned integer on this machine?" 1>&2; exit 1; }
+	{ echo "configure: error: *** How do I get an 8 bit unsigned integer on this machine?" 1>&2; exit 1; }
     fi
     cat >> confdefs.h <<EOF
 #define DBYTE $DODS_BYTE
@@ -2540,7 +2540,7 @@ EOF
 	XDR_FLOAT64=xdr_double
 	XDR_FLOAT32=xdr_float
     else
-	{ echo "configure: error: How do I get floating point types on this machine?" 1>&2; exit 1; }
+	{ echo "configure: error: *** How do I get floating point types on this machine?" 1>&2; exit 1; }
     fi
     cat >> confdefs.h <<EOF
 #define DFLOAT64 $DODS_FLOAT64
@@ -2993,7 +2993,7 @@ EOF
 
       ;;
     *)
-      { echo "configure: error: Bad debug value" 1>&2; exit 1; }
+      { echo "configure: error: *** Bad debug value" 1>&2; exit 1; }
       ;;
     esac
 
