Merge release-3-4 into trunk

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1332,15 +1332,15 @@ _ACEOF
 
 
 
-    echo "$as_me:$LINENO: checking \"for the packages directory\"" >&5
-echo $ECHO_N "checking \"for the packages directory\"... $ECHO_C" >&6
+    echo "$as_me:$LINENO: checking for the packages directory" >&5
+echo $ECHO_N "checking for the packages directory... $ECHO_C" >&6
     # Where does DODS live?
 
     DODS_PACKAGES_DIR=`ls -1d ${dods_relative}src/packages* 2> /dev/null`
     if test -z "$DODS_PACKAGES_DIR"
     then
-	{ { echo "$as_me:$LINENO: error: \"Could not find the third-party packages!\"" >&5
-echo "$as_me: error: \"Could not find the third-party packages!\"" >&2;}
+	{ { echo "$as_me:$LINENO: error: Could not find the third-party packages!" >&5
+echo "$as_me: error: Could not find the third-party packages!" >&2;}
    { (exit 1); exit 1; }; }
     fi
     echo "$as_me:$LINENO: result: $DODS_PACKAGES_DIR" >&5
@@ -1558,8 +1558,20 @@ host_os=`echo $ac_cv_host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
 
 
 
-CFLAGS=${CFLAGS-"-gstabs -O2 $CFLAGS"}
-CXXFLAGS=${CXXFLAGS-"-gstabs -O2 $CXXFLAGS"}
+# Until further notice OS X port doesn't get -gstabs because of an
+# apparent bug in their gcc 3.3 clone (a beta).  If you see this after
+# 1/1/2005, you can probably remove it.
+case "${host_cpu}:${host_vendor}:${host_os}" in
+     powerpc:apple:netbsd*)
+       CFLAGS=${CFLAGS-"-O2 $CFLAGS"}
+       CXXFLAGS=${CXXFLAGS-"-O2 $CXXFLAGS"}
+       break;;
+    *:*:*)
+       CFLAGS=${CFLAGS-"-gstabs -O2 $CFLAGS"}
+       CXXFLAGS=${CXXFLAGS-"-gstabs -O2 $CXXFLAGS"}
+       break;;
+esac
+
 
 
 CXX=${CXX-g++}
@@ -6624,6 +6636,9 @@ echo $ECHO_N "checking for libcurl and its headers... $ECHO_C" >&6
 	# INCS="`$dods_root/bin/curl-config --cflags` $INCS"
 	# AC_SUBST(INCS)		# 09/20/02 jhrg
         LIBS="`$dods_root/bin/curl-config --libs` $LIBS"
+        # 2003/06/13 ERD - added result message
+        echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
     else
 	{ { echo "$as_me:$LINENO: error: Could not find curl-config!" >&5
 echo "$as_me: error: Could not find curl-config!" >&2;}
@@ -6695,9 +6710,22 @@ fi
 
     echo "$as_me:$LINENO: checking for libxml2 and its headers" >&5
 echo $ECHO_N "checking for libxml2 and its headers... $ECHO_C" >&6
-    if test -n "`which xml2-config`"
+    # 2003/06/13 ERD - chaged to handle libxml2 distrib w/ DODS
+    # libxml2 NOT part of DODS distribution
+    #if test -n "`which xml2-config`"
+    # libxml2 IS part of DODS distribution
+    if test -x $dods_root/bin/xml2-config
     then
-        LIBS="`xml2-config --libs` $LIBS"
+        # libxml2 NOT part of DODS distribution
+        #INCS="`xml2-config --cflags` $INCS"
+        #LIBS="`xml2-config --libs` $LIBS"
+        # libxml2 IS part of DODS distribution
+        # INCS="`$dods_root/bin/xml2-config --cflags` $INCS"
+        INCS="-I../../include/libxml2 $INCS"
+        LIBS="`$dods_root/bin/xml2-config --libs` $LIBS"
+        echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
     else
 	{ { echo "$as_me:$LINENO: error: Could not find xml2-config!" >&5
 echo "$as_me: error: Could not find xml2-config!" >&2;}
