Resolved conflicts from the merge of release 3.2.6

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -22,7 +22,7 @@
 # 4. Macros for locating various systems (Matlab, etc.)
 # 5. Macros used to test things about the computer/OS/hardware
 #
-# $Id: configure,v 1.77 2001/06/15 23:49:03 jimg Exp $
+# $Id: configure,v 1.78 2001/08/24 17:46:22 jimg Exp $
 
 # 1. Unidata's macros
 #-------------------------------------------------------------------------
@@ -1574,8 +1574,8 @@ echo "configure:1571: checking for gcc/g++ 2.8 or greater" >&5
 
     case $GCC_VER in
         *egcs*) echo "$ac_t""Found egcs version ${GCC_VER}." 1>&6 ;;
-	2.[7-9]*)   echo "$ac_t""Found gcc/g++ version ${GCC_VER}" 1>&6 ;;
-        *)      { echo "configure: error: must be at least version 2.7.x" 1>&2; exit 1; } ;;
+	[3-9].* | 2.[7-9]*) echo "$ac_t""Found gcc/g++ version ${GCC_VER}" 1>&6 ;;
+        *) { echo "configure: error: must be at least version 2.7.x" 1>&2; exit 1; } ;;
     esac
     
     echo $ac_n "checking for gcc's libgcc.a""... $ac_c" 1>&6
